//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Izgotovleniya
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Izgotovleniya()
        {
            this.Zakaz = new HashSet<Zakaz>();
        }
    
        public int id_Izgotovleniya { get; set; }
        public string nameofizg { get; set; }
        public Nullable<int> ingridient_1 { get; set; }
        public Nullable<int> ingridient_2 { get; set; }
        public Nullable<int> ingridient_3 { get; set; }
        public Nullable<int> ingridient_4 { get; set; }
        public Nullable<int> ingridient_5 { get; set; }
        public Nullable<int> ingridient_6 { get; set; }
        public Nullable<int> ingridient_7 { get; set; }
        public Nullable<int> price { get; set; }
    
        public virtual Produkty Produkty { get; set; }
        public virtual Produkty Produkty1 { get; set; }
        public virtual Produkty Produkty2 { get; set; }
        public virtual Produkty Produkty3 { get; set; }
        public virtual Produkty Produkty4 { get; set; }
        public virtual Produkty Produkty5 { get; set; }
        public virtual Produkty Produkty6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakaz> Zakaz { get; set; }
    }
}
