//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produkty()
        {
            this.Izgotovleniya = new HashSet<Izgotovleniya>();
            this.Izgotovleniya1 = new HashSet<Izgotovleniya>();
            this.Izgotovleniya2 = new HashSet<Izgotovleniya>();
            this.Izgotovleniya3 = new HashSet<Izgotovleniya>();
            this.Izgotovleniya4 = new HashSet<Izgotovleniya>();
            this.Izgotovleniya5 = new HashSet<Izgotovleniya>();
            this.Izgotovleniya6 = new HashSet<Izgotovleniya>();
        }
    
        public int id_Prod { get; set; }
        public string nameofprod { get; set; }
        public Nullable<int> postavshik { get; set; }
        public string kolvosklad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Izgotovleniya> Izgotovleniya { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Izgotovleniya> Izgotovleniya1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Izgotovleniya> Izgotovleniya2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Izgotovleniya> Izgotovleniya3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Izgotovleniya> Izgotovleniya4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Izgotovleniya> Izgotovleniya5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Izgotovleniya> Izgotovleniya6 { get; set; }
        public virtual Postavshsik Postavshsik { get; set; }
    }
}
