//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sotrudnik()
        {
            this.Zakaz = new HashSet<Zakaz>();
        }
    
        public int id_Sotr { get; set; }
        public string name { get; set; }
        public string firstname { get; set; }
        public string secondname { get; set; }
        public string codsotr { get; set; }
        public string pas_num { get; set; }
        public string pas_ser { get; set; }
        public string adress { get; set; }
        public Nullable<int> medbook { get; set; }
        public Nullable<int> dolj { get; set; }
    
        public virtual Doljnost Doljnost { get; set; }
        public virtual MedBook MedBook1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakaz> Zakaz { get; set; }
    }
}
