//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        public int id_Zakaza { get; set; }
        public Nullable<int> id_Izgotovleniya { get; set; }
        public Nullable<int> id_Sotrudnika { get; set; }
        public Nullable<int> id_Klienta { get; set; }
        public string Adress { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Izgotovleniya Izgotovleniya { get; set; }
        public virtual Sotrudnik Sotrudnik { get; set; }
    }
}
